version: "3.9"

services:
  express:
    build:
      context: backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - network
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:14.2
    restart: unless-stopped
    hostname: postgres
    environment:
      - POSTGRES_DB=home
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    expose:
      - "4200"
    ports:
      - "4200:4200"
    networks:
      - network
    depends_on:
      - express

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - network

  influxdb:
    image: influxdb:2.2.0
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    networks:
      - network
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=dip
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Fgp2ozMxmkYnUBkzwLpkx6ydOVXyQqF4-ZPctGjv8-xkirYPYRvoBtrpAHMCr_joYoJMOqZjl8djjuyOx-MR_A==
    healthcheck:
      test: [ "CMD", "influx", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  network:
    driver: bridge
