service:
  #name:  # This should be deprecated in next major release
  logimicInfluxDataBase

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: true
plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221  # Will be default in next major release
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: dev3
  deploymentBucket: aaa44
  serverSideEncryption: AES256
  #iamManagedPolicies:
  #  - 'arn:aws:iam::146240438812:policy/lgmcDynamoFull'
  #  - 'arn:aws:iam::146240438812:policy/lgmcLighting'
  region: us-east-1

functions:
  main:
    handler: index.handler
